"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var node_assert_1 = require("node:assert");
var WorkspaceService_js_1 = require("../WorkspaceService.js");
var service = new WorkspaceService_js_1.WorkspaceService();
var session = service.createSession();
var context = session.getContext();
var summary = service.getWorkspaceSummary();
node_assert_1.strict.equal(summary.name, "BPV4 Workspace");
node_assert_1.strict.equal(summary.version, "1.0.0");
node_assert_1.strict.equal(summary.healthy, true);
node_assert_1.strict.equal(context.configuration.workspaceVersion, "1.0.0");
node_assert_1.strict.equal(session.isReady(), true);
node_assert_1.strict.equal(service.validate(), true);
node_assert_1.strict.equal(service.isHealthy(), true);
console.log("");
console.log("======================================");
console.log("Workspace Service Test PASSED");
console.log("======================================");
